# Generated by Django 3.1 on 2020-11-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmanagement',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
