# Generated by Django 3.1 on 2020-09-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200917_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active',
            new_name='is_active',
        ),
    ]
