# Generated by Django 3.1 on 2020-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200917_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('F', 'F'), ('A', 'A'), ('S', 'S')], default='S', max_length=5),
        ),
    ]
