# Generated by Django 3.1 on 2020-11-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20201107_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairprofile',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
