# Generated by Django 3.1 on 2020-11-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201109_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='bookservice',
            old_name='delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='delete',
            new_name='is_delete',
        ),
    ]
